# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e2ee503943ce61938b5c53fa24bc63e0fd7c428eb009d4d1240ef8003b6a06c1f85ace0873ed29150d0740bcd8cd9c2dd12ee750c26d25251f27a8b618ef47

test:
  secret_key_base: 29615a9e429095a9d48a67ca4f525c0097d4270a971f9f18c1ff6831e4eb40b0e5b505d88f4fc9f5d153ea7846f9425d6f2addc8b6f3dfb5778036ab8e0b329e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
